<a href="https://colab.research.google.com/github/mandem296/AI-ML-Group-Task/blob/master/Feature_extraction_lesson.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
from numpy.linalg import svd 
from sklearn.decomposition import TruncatedSVD,PCA
from numpy import random

In [ ]:
pca=PCA(2)
t_svd=TruncatedSVD(2)

In [ ]:
size=100

In [ ]:
generate=np.random.uniform(100,500,size)

Form random datasets

Place datasets in a pandas dataframe

Visualize data in a pandas

In [ ]:
data={'Location':generate,'Size':generate,'Mall Near':generate,'Ambience':generate,'Rent':generate}

In [ ]:
df=pd.DataFrame(data)

In [ ]:
df

      Location        Size   Mall Near    Ambience        Rent
0   155.653469  155.653469  155.653469  155.653469  155.653469
1   238.238727  238.238727  238.238727  238.238727  238.238727
2   136.509952  136.509952  136.509952  136.509952  136.509952
3   380.936671  380.936671  380.936671  380.936671  380.936671
4   359.109365  359.109365  359.109365  359.109365  359.109365
..         ...         ...         ...         ...         ...
95  163.773517  163.773517  163.773517  163.773517  163.773517
96  130.827212  130.827212  130.827212  130.827212  130.827212
97  187.967811  187.967811  187.967811  187.967811  187.967811
98  430.189488  430.189488  430.189488  430.189488  430.189488
99  329.685950  329.685950  329.685950  329.685950  329.685950

[100 rows x 5 columns]

Removing the target

In [ ]:
df.drop("Rent", axis=1, inplace=True)

In [ ]:
df

      Location        Size   Mall Near    Ambience
0   155.653469  155.653469  155.653469  155.653469
1   238.238727  238.238727  238.238727  238.238727
2   136.509952  136.509952  136.509952  136.509952
3   380.936671  380.936671  380.936671  380.936671
4   359.109365  359.109365  359.109365  359.109365
..         ...         ...         ...         ...
95  163.773517  163.773517  163.773517  163.773517
96  130.827212  130.827212  130.827212  130.827212
97  187.967811  187.967811  187.967811  187.967811
98  430.189488  430.189488  430.189488  430.189488
99  329.685950  329.685950  329.685950  329.685950

[100 rows x 4 columns]

In [ ]:
pca.fit_transform(df)

array([[ 2.99539360e+02,  2.71080281e-13],
       [ 1.34368844e+02,  4.63356033e-16],
       [ 3.37826393e+02, -8.09841334e-15],
       [-1.51027045e+02,  1.56052169e-16],
       [-1.07372432e+02, -8.15038283e-16],
       [-2.32602870e+02,  8.14326215e-16],
       [ 3.43286011e+02, -1.40262325e-14],
       [ 8.30066266e+01, -8.76978308e-16],
       [-1.00174085e+02, -9.13699448e-16],
       [ 3.91175085e+02,  6.29992087e-15],
       [-2.96648556e+02,  3.78714412e-16],
       [ 2.01310998e+02, -6.92675318e-15],
       [ 4.88372715e+01, -2.22818808e-15],
       [-2.44554255e+02, -1.01409858e-15],
       [ 4.63728990e+01, -1.67823459e-15],
       [ 1.35238128e+02, -2.95768295e-15],
       [-1.48263845e+02, -6.23301593e-16],
       [ 2.99288440e+02, -1.02076089e-14],
       [-2.65093083e+02,  6.41451452e-15],
       [ 4.06822999e+01, -8.82313529e-16],
       [-1.07054389e+02,  3.90713021e-15],
       [-5.35844017e+01,  1.20502607e-15],
       [-2.50054568e+02,  7.38627109e-16],
       [-3.85491631e+02,  1.13835897e-15],
       [-9.44215934e+01, -1.65006522e-15],
       [-1.64608939e+02,  4.30839791e-15],
       [ 2.23915380e+02, -8.43526246e-15],
       [ 2.95082148e+01, -4.30163130e-16],
       [-3.61741431e+02,  4.90289365e-15],
       [ 2.67390323e+02, -9.30268881e-16],
       [-1.61670732e+02,  1.52790846e-15],
       [-1.73341286e+01,  5.66864907e-16],
       [-3.10541019e+02,  3.44549209e-15],
       [-2.07151459e+02, -3.09656363e-15],
       [-1.57338146e+02,  2.58647349e-15],
       [ 4.03163987e+02, -1.05813823e-14],
       [-3.38109774e+02,  4.38349676e-15],
       [-2.52373903e+02,  3.67556700e-15],
       [-2.31274779e+02, -2.33382043e-15],
       [-1.09116775e+02,  3.83697705e-15],
       [ 2.55915626e+02, -5.09477346e-15],
       [ 3.77850801e+02, -1.67318927e-14],
       [-3.39953897e+02,  9.39990140e-15],
       [ 1.38451605e+02,  1.13569837e-15],
       [-3.35129973e+02,  2.35373003e-15],
       [-5.98359014e+01,  1.92625521e-15],
       [-3.75818644e+01, -1.78215635e-16],
       [ 3.70825007e+02, -1.10487892e-14],
       [ 1.24498901e+02, -4.33210115e-15],
       [-1.51185126e+02,  3.29643807e-15],
       [ 2.49364092e+02, -3.60352786e-15],
       [-2.55095059e+02, -2.50258829e-15],
       [-2.56812716e+02,  1.44573439e-16],
       [-8.78445556e+01, -6.15723475e-16],
       [-3.59930155e+02,  1.18104077e-14],
       [ 1.39361456e+02, -2.10141727e-15],
       [ 4.04598248e+02,  1.25969245e-15],
       [ 3.42584532e+02, -8.98556474e-15],
       [-2.52609248e+02,  6.28134966e-15],
       [ 3.58913310e+02,  6.15365991e-15],
       [-3.61438805e+02,  6.44049594e-15],
       [ 4.03287933e+02, -1.52329743e-14],
       [ 1.33718532e+01, -1.82137931e-16],
       [-1.82925095e+02, -1.86699312e-16],
       [-2.48508308e+02,  8.15253246e-15],
       [ 3.69027856e+02,  1.63953521e-15],
       [ 2.92005984e+02, -8.10184831e-15],
       [-2.51386605e+02,  2.35515476e-15],
       [ 2.72419591e+02, -4.48329735e-15],
       [-2.17550638e+02, -5.76619533e-16],
       [ 7.45484068e+01,  1.21856243e-16],
       [ 1.24288273e+02, -3.61388812e-15],
       [-2.91372502e+02, -2.94823439e-16],
       [ 1.65166614e+02,  1.02813170e-15],
       [ 5.42335044e+01, -1.59699361e-15],
       [ 8.78563937e+01, -2.80518378e-16],
       [ 5.11689295e+01,  2.25718792e-16],
       [ 1.64116130e+02, -3.22284387e-15],
       [-6.72358081e+01,  2.35163659e-15],
       [-3.32236865e+02, -6.47475499e-16],
       [ 2.86098382e+02,  2.36153861e-15],
       [ 3.69862335e+02, -5.36418225e-15],
       [-2.02425211e+02,  9.15071464e-15],
       [-2.80093769e+02,  3.09567247e-15],
       [ 2.82325168e+02, -3.93946579e-15],
       [ 1.34477511e+02,  4.28767070e-16],
       [-1.07645799e+02,  4.61669541e-15],
       [ 2.82647862e+01,  1.68301330e-16],
       [-2.25288574e+02,  5.97165197e-16],
       [ 1.25417598e+02, -4.58608993e-15],
       [ 7.43975268e+01, -1.33219969e-17],
       [-1.24520586e+02,  1.00231651e-15],
       [-3.75656385e+01,  4.26964845e-16],
       [ 1.61403322e+02, -4.96450549e-15],
       [-3.36578932e+02,  1.41186244e-14],
       [ 2.83299264e+02,  2.24530394e-15],
       [ 3.49191875e+02, -1.14615541e-14],
       [ 2.34910676e+02,  3.80105323e-16],
       [-2.49532679e+02,  1.15861174e-14],
       [-4.85256020e+01,  9.38612091e-16]])

In [ ]:
t_svd.fit_transform(df)

array([[ 3.11306937e+02, -2.67421435e-15],
       [ 4.76477453e+02, -2.58523035e-14],
       [ 2.73019905e+02, -1.52872876e-14],
       [ 7.61873343e+02, -5.25453845e-14],
       [ 7.18218729e+02, -4.45428604e-15],
       [ 8.43449167e+02, -3.24151417e-14],
       [ 2.67560286e+02, -1.36196396e-14],
       [ 5.27839671e+02, -2.83082373e-14],
       [ 7.11020382e+02, -3.10918561e-14],
       [ 2.19671213e+02, -1.44260687e-14],
       [ 9.07494854e+02, -6.28853283e-14],
       [ 4.09535300e+02, -4.14861576e-14],
       [ 5.62009026e+02, -3.21064738e-14],
       [ 8.55400553e+02, -5.92712595e-14],
       [ 5.64473399e+02, -2.62424694e-14],
       [ 4.75608169e+02, -2.24713004e-14],
       [ 7.59110143e+02, -7.90338747e-14],
       [ 3.11557858e+02, -1.73330092e-14],
       [ 8.75939380e+02, -5.36681679e-14],
       [ 5.70163998e+02, -2.96153242e-14],
       [ 7.17900686e+02, -3.34630731e-14],
       [ 6.64430699e+02, -1.46017128e-15],
       [ 8.60900865e+02, -2.68958374e-14],
       [ 9.96337928e+02, -4.88892218e-14],
       [ 7.05267891e+02, -2.96403997e-14],
       [ 7.75455236e+02, -2.96797764e-14],
       [ 3.86930918e+02, -1.30753921e-14],
       [ 5.81338083e+02, -3.42079404e-14],
       [ 9.72587729e+02, -5.12875485e-14],
       [ 3.43455975e+02, -1.43767731e-14],
       [ 7.72517029e+02, -6.30608630e-14],
       [ 6.28180426e+02, -3.43539279e-14],
       [ 9.21387317e+02, -4.82149289e-14],
       [ 8.17997757e+02, -3.40610379e-14],
       [ 7.68184443e+02, -5.10397715e-14],
       [ 2.07682310e+02, -1.56391988e-14],
       [ 9.48956071e+02, -5.44058692e-14],
       [ 8.63220200e+02, -3.14976574e-14],
       [ 8.42121077e+02, -5.79864384e-14],
       [ 7.19963073e+02, -5.30973075e-14],
       [ 3.54930672e+02, -4.11344726e-14],
       [ 2.32995497e+02, -2.27353148e-15],
       [ 9.50800195e+02, -4.46000368e-14],
       [ 4.72394693e+02, -1.07895831e-15],
       [ 9.45976271e+02, -4.70249425e-14],
       [ 6.70682199e+02, -5.11950246e-14],
       [ 6.48428162e+02, -5.49586075e-14],
       [ 2.40021291e+02, -1.20694599e-14],
       [ 4.86347396e+02, -2.77614257e-14],
       [ 7.62031424e+02, -2.82955738e-14],
       [ 3.61482206e+02, -2.76825125e-14],
       [ 8.65941356e+02, -3.48303523e-14],
       [ 8.67659014e+02, -2.80865084e-14],
       [ 6.98690853e+02, -5.65419221e-14],
       [ 9.70776452e+02, -5.41106071e-14],
       [ 4.71484842e+02, -6.21589097e-15],
       [ 2.06248050e+02, -6.08309709e-15],
       [ 2.68261766e+02, -1.37052659e-14],
       [ 8.63455546e+02, -5.22961854e-14],
       [ 2.51932987e+02, -1.53578215e-14],
       [ 9.72285103e+02, -6.66535253e-14],
       [ 2.07558365e+02, -1.49785573e-14],
       [ 5.97474444e+02, -3.28489906e-14],
       [ 7.93771393e+02, -3.23898188e-14],
       [ 8.59354605e+02, -5.30394002e-14],
       [ 2.41818442e+02, -1.28802665e-14],
       [ 3.18840313e+02, -1.33591624e-14],
       [ 8.62232903e+02, -2.84058567e-14],
       [ 3.38426707e+02, -2.75702249e-14],
       [ 8.28396936e+02, -2.75519566e-14],
       [ 5.36297891e+02, -3.19787534e-14],
       [ 4.86558025e+02,  7.12797379e-17],
       [ 9.02218799e+02, -6.79481745e-14],
       [ 4.45679684e+02, -1.51358168e-15],
       [ 5.56612793e+02, -3.19036694e-14],
       [ 5.22989904e+02, -3.00840855e-14],
       [ 5.59677368e+02, -3.16992092e-14],
       [ 4.46730167e+02, -5.02316946e-14],
       [ 6.78082106e+02, -2.62148123e-14],
       [ 9.43083163e+02, -1.37666947e-14],
       [ 3.24747916e+02, -1.09809019e-14],
       [ 2.40983963e+02,  1.56925737e-17],
       [ 8.13271508e+02, -2.81162750e-14],
       [ 8.90940066e+02, -1.29195955e-14],
       [ 3.28521130e+02, -1.62691419e-14],
       [ 4.76368786e+02, -2.17238870e-14],
       [ 7.18492096e+02, -3.50569203e-14],
       [ 5.82581511e+02, -5.72117601e-14],
       [ 8.36134872e+02, -2.31071662e-14],
       [ 4.85428699e+02, -2.62763187e-14],
       [ 5.36448771e+02, -3.39781463e-14],
       [ 7.35366884e+02, -2.18983521e-14],
       [ 6.48411936e+02, -5.33204895e-14],
       [ 4.49442976e+02, -2.63436225e-14],
       [ 9.47425230e+02, -5.99761390e-14],
       [ 3.27547034e+02, -2.08713907e-15],
       [ 2.61654423e+02, -1.22472389e-14],
       [ 3.75935622e+02, -1.51835800e-14],
       [ 8.60378976e+02, -7.83549136e-14],
       [ 6.59371900e+02, -2.32931074e-14]])